import { Inter } from "next/font/google";
import "./globals.css";
import Providers from "./utils/providers";
// import { UserProvider } from "@auth0/nextjs-auth0/client";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
// `${inter.className}`
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      {/* <UserProvider> */}
        <body className={`${inter.className}`}>
          <Providers>{children}</Providers>
        </body>
      {/* </UserProvider> */}
    </html>
  );
}
